**Language Selection**:An Indic accented English speech dataset.

**Data Acquisition**:Downloded the Svarah dataset


In [4]:
import json
import os
import json
import os
import random
from pathlib import Path
!pip install pydub

from pydub import AudioSegment

**Data Preparation:**
		Pre-processed  the data to ensure clean, normalised audio inputs and properly formatted transcripts.
    
**data split:**
		Splited the data into training, validation, and testing sets in an 80/10/10 ratio.

In [5]:
# Paths to manifest files and desired output directories
manifest_files = ['svarah_manifest.json', 'saa_l1_manifest.json']
output_dir = 'processed_data/'
Path(output_dir).mkdir(parents=True, exist_ok=True)



In [6]:
TARGET_SAMPLE_RATE = 22050

In [13]:
def load_manifest(manifest_path="/content/saa_l1_manifest.json"):
    """Loads and parses the JSON manifest."""
    with open(manifest_path, 'r', encoding='utf-8') as f:
        import json
        data = [json.loads(line) for line in f] # This line was indented, causing the error.
    return data # Removing the extra return and data assignment inside with open

In [18]:
from pydub import AudioSegment
import os

# Define target sample rate and output directory
TARGET_SAMPLE_RATE = 16000  # Example, modify according to your requirement
output_dir = '/content/drive/MyDrive/audio'  # Specify your output directory

def preprocess_audio(output_dir):
    """Resamples audio if necessary and returns path to processed file."""
    audio = AudioSegment.from_wav()  # Load the audio file
    if audio.frame_rate != TARGET_SAMPLE_RATE:
        audio = audio.set_frame_rate(TARGET_SAMPLE_RATE)  # Resample if needed

    # Save resampled audio
    processed_path = os.path.join(output_dir, os.path.basename(output_dir))
    audio.export(processed_path, format="wav")  # Export as WAV
    return processed_path


In [19]:
def split_data(data, train_ratio=0.8, val_ratio=0.1):
    """Split data into train, validation, and test sets."""
    random.shuffle(data)
    total = len(data)
    train_end = int(train_ratio * total)
    val_end = train_end + int(val_ratio * total)
    return data[:train_end], data[train_end:val_end], data[val_end:]

In [38]:
from pydub import AudioSegment
import os

# Define target sample rate and output directory
TARGET_SAMPLE_RATE = 16000  # Example, modify according to your requirement
from pydub import AudioSegment
import os

# Define target sample rate and output directory
TARGET_SAMPLE_RATE = 16000  # Example, modify according to your requirement
output_dir = '/content/drive/MyDrive/audio'  # Specify your output directory

def preprocess_audio(audio_file_path, output_dir): # Added audio_file_path as argument
    """Resamples audio if necessary and returns path to processed file."""
    audio = AudioSegment.from_wav(audio_file_path)  # Load the audio file using the provided path
    if audio.frame_rate != TARGET_SAMPLE_RATE:
        audio = audio.set_frame_rate(TARGET_SAMPLE_RATE)  # Resample if needed

    # Save resampled audio
    processed_path = os.path.join(output_dir, os.path.basename(audio_file_path)) # Use audio_file_path for basename
    audio.export(processed_path, format="wav")  # Export as WAV
    return processed_path
    if audio.frame_rate != TARGET_SAMPLE_RATE:
        audio = audio.set_frame_rate(TARGET_SAMPLE_RATE)  # Resample if needed

    # Save resampled audio
    processed_path = os.path.join(output_dir, os.path.basename('/content/drive/MyDrive/audio')) # Use audio_file_path for basename
    audio.export(processed_path, format="wav")  # Export as WAV
    return processed_path


In [34]:
# Split data into training, validation, and test sets
train_data, val_data, test_data = split_data(all_data)

In [35]:
def save_manifest(data, filename):
    with open(filename, 'w', encoding='utf-8') as f:
        for entry in data:
            json.dump(entry, f)
            f.write('\n')

In [36]:
save_manifest(train_data, os.path.join(output_dir, 'train_manifest.json'))
save_manifest(val_data, os.path.join(output_dir, 'val_manifest.json'))
save_manifest(test_data, os.path.join(output_dir, 'test_manifest.json'))

In [37]:
print("Data preparation completed. Train, validation, and test manifests saved in:", output_dir)

Data preparation completed. Train, validation, and test manifests saved in: /content/drive/MyDrive/audio


4.**Model Configuration**
	•	Set up the VITS model by cloning the VITS GitHub repository and configuring it to handle the chosen language and dataset specifics.

In [42]:
!git clone https://github.com/jaywalnut310/vits.git
!cd vits


Cloning into 'vits'...
remote: Enumerating objects: 81, done.
remote: Total 81 (delta 0), reused 0 (delta 0), pack-reused 81 (from 1)
Receiving objects: 100% (81/81), 3.33 MiB | 17.88 MiB/s, done.
Resolving deltas: 100% (22/22), done.


In [45]:
!apt-get update
!apt-get install python3.10-venv


Get:1 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Hit:2 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Get:4 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,626 B]
Get:5 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]
Get:6 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease [1,581 B]
Get:7 https://r2u.stat.illinois.edu/ubuntu jammy InRelease [6,555 B]
Hit:8 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:9 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Get:10 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1,163 kB]
Hit:11 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Get:12 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [2,391 kB]
Get:13 https://cloud.r-project.org/bin/linux/ubuntu ja

In [46]:
!python3 -m venv venv


In [47]:
!venv/bin/pip install --upgrade pip


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 18.4 MB/s eta 0:00:00
  Attempting uninstall: pip
    Found existing installation: pip 22.0.2
    Uninstalling pip-22.0.2:
      Successfully uninstalled pip-22.0.2


In [48]:
!pip install torch librosa numpy


In [49]:
!ls

281474976883984_f3332_chunk_0.txt   281474976893839_f3333_chunk_2.txt
281474976883984_f3332_chunk_0.wav   281474976893839_f3333_chunk_2.wav
281474976883989_f3285_chunk_0.txt   281474976893839_f3333_chunk_3.txt
281474976883989_f3285_chunk_0.wav   281474976893839_f3333_chunk_3.wav
281474976883989_f3285_chunk_1.txt   281474976893850_f3335_chunk_0.txt
281474976883989_f3285_chunk_1.wav   281474976893850_f3335_chunk_0.wav
281474976883989_f3285_chunk_2.txt   281474976893850_f3335_chunk_10.txt
281474976883989_f3285_chunk_2.wav   281474976893850_f3335_chunk_10.wav
281474976883989_f3285_chunk_3.txt   281474976893850_f3335_chunk_11.txt
281474976883989_f3285_chunk_3.wav   281474976893850_f3335_chunk_11.wav
281474976883989_f3285_chunk_4.txt   281474976893850_f3335_chunk_1.txt
281474976883989_f3285_chunk_4.wav   281474976893850_f3335_chunk_1.wav
281474976883989_f3285_chunk_5.txt   281474976893850_f3335_chunk_2.txt
281474976883989_f3285_chunk_5.wav   281474976893850_f3335_chunk_2.wav
281474976884119_

5.	**Model Training:**
	•	Train the model using the prepared datasets while monitoring for performance issues and making necessary adjustments.

In [57]:
cd vits


/content/vits


In [58]:
!ls


attentions.py  filelists	mel_processing.py  preprocess.py     text	    utils.py
commons.py     inference.ipynb	models.py	   README.md	     train_ms.py
configs        LICENSE		modules.py	   requirements.txt  train.py
data_utils.py  losses.py	monotonic_align    resources	     transforms.py


In [61]:
!python train.py --config /content/vits/configs/config.json --data_dir /content/drive/MyDrive/audio


2024-11-06 04:33:22.235842: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-11-06 04:33:22.259688: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-11-06 04:33:22.266805: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-11-06 04:33:22.283449: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-11-06 04:33:23.876245: W tensorflow/compiler/tf2

In [64]:
# Import necessary libraries (assuming you are using TensorFlow/Keras)
import tensorflow as tf
from tensorflow import keras
import numpy as np # Import numpy for data manipulation


# Define and compile the model
# This is a simple example, replace with your desired model architecture
model = keras.Sequential([
    keras.layers.Dense(128, activation='relu', input_shape=(784,)),
    keras.layers.Dense(10, activation='softmax')
])
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])


# Load your data (replace with your actual data loading logic)
# Assuming you have training data in X_train and y_train

# Example using dummy data for demonstration
# Replace this with your actual data loading process
num_samples = 1000
X_train = np.random.rand(num_samples, 784) # Create random data for X_train
y_train = np.random.randint(0, 10, size=(num_samples,)) # Create random labels for y_train
y_train = keras.utils.to_categorical(y_train, num_classes=10) # One-hot encode labels



# Train the model using model.fit()
model.fit(X_train, y_train, epochs=10)

Epoch 1/10


/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


32/32 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.1035 - loss: 2.4369
Epoch 2/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.1199 - loss: 2.3075
Epoch 3/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.1484 - loss: 2.2505
Epoch 4/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.1942 - loss: 2.2163
Epoch 5/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.2054 - loss: 2.1815
Epoch 6/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.2792 - loss: 2.0795
Epoch 7/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.3104 - loss: 2.0384
Epoch 8/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3701 - loss: 1.9334
Epoch 9/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4102 - loss: 1.8940
Epoch 10/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5075 - loss: 1.7921


In [65]:
model.save('model.h5')  # Or the preferred method you're using to save your model


6.	**Model Evaluation:**
	•	Evaluate the model using validation and test sets to ensure it meets quality standards in audio synthesis.


In [68]:
import tensorflow as tf
from tensorflow import keras
import numpy as np # Import numpy for data manipulation


# Define and compile the model
# This is a simple example, replace with your desired model architecture
model = keras.Sequential([
    keras.layers.Dense(128, activation='relu', input_shape=(784,)),
    keras.layers.Dense(10, activation='softmax')
])
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])


# Load your data (replace with your actual data loading logic)
# Assuming you have training data in X_train and y_train

# Example using dummy data for demonstration
# Replace this with your actual data loading process
num_samples = 1000
X_train = np.random.rand(num_samples, 784) # Create random data for X_train
y_train = np.random.randint(0, 10, size=(num_samples,)) # Create random labels for y_train
y_train = keras.utils.to_categorical(y_train, num_classes=10) # One-hot encode labels

# **Prepare validation and test data**
# **Replace with your actual data loading and splitting logic**
# **Example using dummy data for demonstration**
num_val_samples = 200
num_test_samples = 200

# Split data into training, validation, and test sets
validation_data = X_train[:num_val_samples]
validation_labels = y_train[:num_val_samples]
test_data = X_train[num_val_samples : num_val_samples + num_test_samples]
test_labels = y_train[num_val_samples : num_val_samples + num_test_samples]
X_train = X_train[num_val_samples + num_test_samples:]
y_train = y_train[num_val_samples + num_test_samples:]



# Train the model using model.fit()
model.fit(X_train, y_train, epochs=10)

# Evaluate the model
val_loss, val_accuracy = model.evaluate(validation_data, validation_labels)
print(f"Validation Loss: {val_loss}, Validation Accuracy: {val_accuracy}")

test_loss, test_accuracy = model.evaluate(test_data, test_labels)
print(f"Test Loss: {test_loss}, Test Accuracy: {test_accuracy}")

Epoch 1/10


/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


19/19 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.0773 - loss: 2.5923    
Epoch 2/10
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.1026 - loss: 2.3302 
Epoch 3/10
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.1597 - loss: 2.2530 
Epoch 4/10
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.2162 - loss: 2.2055 
Epoch 5/10
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.2526 - loss: 2.1477
Epoch 6/10
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.2509 - loss: 2.1352 
Epoch 7/10
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3052 - loss: 2.0760 
Epoch 8/10
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.3236 - loss: 2.0608
Epoch 9/10
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3730 - loss: 1.9770 
Epoch 10/10
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3890 - loss: 1.9164 
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0881 - loss: 2.5455  
Validation Loss: 2.5181632041931152, Validation Accuracy: 0.09000000357627869
7/7 ━━━━

In [69]:
from keras.optimizers import Adam
optimizer = Adam(learning_rate=0.001)
model.compile(optimizer=optimizer, loss='your_loss_function', metrics=['accuracy'])


7.**Optimization and Refinement:**
	•	Refine the model based on feedback and testing to improve its accuracy and performance.

In [78]:


# Function to load and extract features from an audio file
def extract_mel_spectrogram(audio_file):
    # Load the audio file
    y, sr = librosa.load(audio_file, sr=None)  # y is the audio signal, sr is the sample rate

    # Extract Mel spectrogram (128 Mel bands)
    # Pass 'y' and 'sr' as keyword arguments
    mel_spectrogram = librosa.feature.melspectrogram(y=y, sr=sr, n_mels=128)

    # Convert the Mel spectrogram to decibel scale
    log_mel_spectrogram = librosa.power_to_db(mel_spectrogram, ref=np.max)

    # Return the Mel spectrogram (we transpose it to get time_steps x features)
    return log_mel_spectrogram.T  # This is a 2D array: (time_steps, 128)

# Example: Load an audio file and extract its features
audio_file = '/content/281474976884119_f3327_chunk_0.wav'  # Replace with the path to your audio file
train_data = extract_mel_spectrogram(audio_file)

# Print the shape of the feature array
print(train_data.shape)  # Output shape: (time_steps, 128)


(340, 128)


In [79]:
# Example list of phonemes (labels) corresponding to the audio file
train_labels = ['h', 'e', 'l', 'l', 'o']  # Phonemes for the word 'hello'


In [80]:
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical

# Encode the phoneme labels into integers
label_encoder = LabelEncoder()
encoded_labels = label_encoder.fit_transform(train_labels)

# Optionally, convert the encoded labels to one-hot encoding
one_hot_labels = to_categorical(encoded_labels, num_classes=len(label_encoder.classes_))

# Print encoded labels and their one-hot version
print(encoded_labels)  # [0, 1, 2, 2, 3] (example integer encoding)
print(one_hot_labels)  # [[1, 0, 0, 0], [0, 1, 0, 0], ...] (one-hot encoding)


[1 0 2 2 3]
[[0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [5]:
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical
!pip install praatio
import librosa
  # Import tgio module from praatio
import numpy as np

# ... (rest of the code remains the same)

def prepare_data_with_forced_alignment(audio_file, textgrid_file):
    """
    Prepares training data using forced alignment.

    Args:
        audio_file (str): Path to the audio file.
        textgrid_file (str): Path to the TextGrid file.

    Returns:
        tuple: (train_data, train_labels)
    """

    # Load audio and TextGrid
    y, sr = librosa.load(audio_file, sr=None)
    tg = tgio.openTextgrid(textgrid_file) # Use tgio.openTextgrid

    # ... (rest of the code remains the same)

# ... (rest of the code remains the same)


8.	**Deployment:**
	•	Prepare the model for deployment in a way that allows users to easily convert WAV audio to FLAC using a WebSocket connection.

In [8]:
!pip install websockets pydub


In [14]:
pip install nest_asyncio


In [18]:
!pip install pyngrok
